### ISSUE TITLE
Curious about plans to fill out READme and suggestion

### ISSUE THREAD

**Issue by shannonbux** [datocms/snipcart-gatsby-demo#4]
Hello!

I just used Gatsby Cloud and have been playing around with this demo site; first of all, let me say I love the design and animations. So fun. Reminds me of my childhood in late 80's early 90's :).

I just noticed a couple improvements that could be made; I wouldn't even call them issues:

1. When clicking an image of socks it just adds it to the cart, which is not what I expected. I expected it to just show me details about that sock. Not a bug, just a design idea. 

2. The GitHub READme is pretty sparse, and I think if it were more similar to this one it might have helpful information: https://github.com/datocms/gatsby-portfolio

**Comment by matjack1** [comment]
Hello @shannonbux ! :)

Thank you for the suggestion. Yes, we need to improve here. I'm going through our demos these days to improve them. I've just added the Gatsby ones here: https://www.datocms.com/docs/static-generators/gatsbyjs/examples

But sure we need to improve this readme! You are right. Also about the suggestion you are right, but it would require us to create a new page :) So I agree, but not sure if we have the capacity to work on this soon.

**Comment by shannonbux** [comment]
Hi Matteo! Thank you, and of course, I don't think it is a high priority,
just something I observed and thought might be worth passing along (I'm
sure you already knew both of those suggestions yourself though :)

**Comment by matjack1** [comment]
Readme now makes more sense :) Thank you for opening this!

**Comment by shannonbux** [comment]
thank you!
