### ISSUE TITLE
Can you provide instructions for how to link this site to our own SnipCart account?

### ISSUE THREAD

**Issue by cmarabate** [datocms/snipcart-gatsby-demo#6]
Sorry about submitting this as an issue. I'm sure this isn't an actual issue and purely me not understanding how SnipCart works but...

I used the "Deploy with DatoCMS" button to deploy a copy of the site to Netlify. Then I added the domain of the site to my SnipCart account and tried placing a test order and this is what I got...
![image](https://user-images.githubusercontent.com/12236062/79247412-7d1cb580-7e48-11ea-9b33-464497056bf4.png)

I couldn't find anywhere that you mention how to link this site to our own SnipCart account. Could you please include instructions for this in your README.md file?

Thanks,

Chris

**Comment by matjack1** [comment]
hello @cmarabate !

Have a look at this blog post to give you more insights on how this works: https://www.datocms.com/blog/static-ecommerce-website-snipcart-gatsbyjs-datocms

I'm going to link it in the README, thanks!

**Comment by cmarabate** [comment]
Thanks, I got it working!
